// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGtnegX_0lB_ac_i22E7p9a6SXdROKrK4',
    appId: '1:1012475868227:web:01708c87e4c99cde7310f6',
    messagingSenderId: '1012475868227',
    projectId: 'tide-385d5',
    authDomain: 'tide-385d5.firebaseapp.com',
    storageBucket: 'tide-385d5.firebasestorage.app',
    measurementId: 'G-P2BW80DZ5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFzDdooy7ciVk8WEYUSSOVbGxAMazqytc',
    appId: '1:1012475868227:android:b0cce0bc276353027310f6',
    messagingSenderId: '1012475868227',
    projectId: 'tide-385d5',
    storageBucket: 'tide-385d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaWIUAmg64Etq79jy1k2ounE31W2Qc7LE',
    appId: '1:1012475868227:ios:278fa19be986b84a7310f6',
    messagingSenderId: '1012475868227',
    projectId: 'tide-385d5',
    storageBucket: 'tide-385d5.firebasestorage.app',
    iosBundleId: 'com.tideup.tideUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaWIUAmg64Etq79jy1k2ounE31W2Qc7LE',
    appId: '1:1012475868227:ios:278fa19be986b84a7310f6',
    messagingSenderId: '1012475868227',
    projectId: 'tide-385d5',
    storageBucket: 'tide-385d5.firebasestorage.app',
    iosBundleId: 'com.tideup.tideUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGtnegX_0lB_ac_i22E7p9a6SXdROKrK4',
    appId: '1:1012475868227:web:a4264fcfa34f99a37310f6',
    messagingSenderId: '1012475868227',
    projectId: 'tide-385d5',
    authDomain: 'tide-385d5.firebaseapp.com',
    storageBucket: 'tide-385d5.firebasestorage.app',
    measurementId: 'G-6SF542TJG2',
  );
}
