// File generated by FlutterFire CLI (mock placeholders for immediate compilation).
// To populate with your live credentials:
// 1. Install FlutterFire CLI (dart pub global activate flutterfire_cli)
// 2. Run: flutterfire configure
// This will automatically overwrite this file with your actual Firebase project settings.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGtnegX_0lB_ac_i22E7p9a6SXdROKrK4',
    appId: '1:1012475868227:web:01708c87e4c99cde7310f6',
    messagingSenderId: '1012475868227',
    projectId: 'tide-385d5',
    authDomain: 'tide-385d5.firebaseapp.com',
    storageBucket: 'tide-385d5.firebasestorage.app',
    measurementId: 'G-P2BW80DZ5W',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PLACEHOLDER-API-KEY-ANDROID',
    appId: '1:1234567890:android:1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'Tide-placeholder',
    storageBucket: 'Tide-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER-API-KEY-IOS',
    appId: '1:1234567890:ios:1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'Tide-placeholder',
    storageBucket: 'Tide-placeholder.appspot.com',
    iosBundleId: 'com.Tide.tide',
  );
}
